### ISSUE TITLE
[S] Update booking times for summer schedule in DUP

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-reso-public#359]
Text on booking page in DUP public need to be changed for AM and PM from 12pm to 1pm.

Change AM to: 7am - 1pm (depart by 1pm)

Change PM to: Arrive after 1pm

change text on the booking page here: 

![Image](https://github.com/bcgov/parks-reso-public/assets/38668130/5804a1d1-69a5-4635-814b-11c09c92b862)

## Acceptance Criteria

- 12pm is changed to 1pm on booking page
- backend logic reflects 1pm as well
  - this affects what time passes transition from active to expired status

## Notes
- similar to: https://github.com/bcgov/parks-reso-public/pull/210 from last year and reverse of https://github.com/bcgov/parks-reso-public/issues/280

**Comment by manuji** [comment]
Tested on TEST:
* Verified that the FE updates have been done and copy shows 1pm instead of 12pm. 
* Pending verification of the logic for pass expiry.

**Comment by cameronpettit** [comment]
I'm actually not sure about this one. I think we had it set up so that you could check in passes before the slot opened (that would make things simpler for the park operators). I took a quick look at the check in code and I cant see anywhere it verifies the time of check-in. @danieltruong may be able to jog my memory on this.

**Comment by manuji** [comment]
During the stand-up it was confirmed that it's the expected behaviour. Passing to PO review.

**Comment by JLWade** [comment]
looks good - moving to done
