### ISSUE TITLE
DUP- Trail passes show incorrect number of available passes

### ISSUE THREAD

**Issue by manuji** [bcgov/parks-reso-public#368]
While testing the DUP, came across this issue. 

Scenario:
* Navigate to a Park from DUP admin, set the any pass type from AM, PM or All day trail passes to be less than 4. 
* Save changes and navigate to the Public site. 
* Now try to book a trail passes and check the options displayed in the "Number of Passes Required" field

Expected:
* If the number of passes less than 4 then the dropdown should display the options respective to the number of passes actually available. 

Issue:
* The Dropdown first shows all the default options regardless of the number of passes available for the day. When user tries to book passes more than available, at the last step it shows the error message for passing being unavailable. Afterwards the dropdown starts showing the correct options in the dropdown. 
Watch the video for further details. 

https://github.com/bcgov/parks-reso-public/assets/65190263/ee9e4bf1-8ad4-49a7-9a1b-06c9c7708207

**Comment by cameronpettit** [comment]
This error only occurs in the front end and is just a misrepresentation of the actual number of passes available. It only happens when you look ahead at a future date that has no bookings for it yet - the front end assumes that the max number of trail passes one person can book (4) is available if no reservation object exists.

It will also only occur if the total number of base passes allotted to a trail facility is less than 4, which likely will never occur. 

This error does not occur for the current date.

This has been fixed by adding a clause where the front end always shows the minimum of 3 possible pass availability values: the actual number of passes available, the maximum number of passes allotted to the facility, and the max number a user can book at once (hardcoded to 4).

Waiting for the pass timer stuff to be merged before this is merged.

**Comment by JLWade** [comment]
thanks for the context Cam!

**Comment by cameronpettit** [comment]
Complete but moving to blocked until the hold pass timer stuff successfully merges.
