### ISSUE TITLE
DUP email confirmation shows incorrect reservation date

### ISSUE THREAD

**Issue by manuji** [bcgov/parks-reso-public#471]
Scenario:
* Navigate to the DUP public website on TEST environment: https://test-dup.bcparks.ca/dayuse/
* Book a pass in Garibaldi park, Cheakamus subarea. 
* Check the reservation date displayed on the booking confirmation page and the email confirmation. 
* Verify if the dates displayed are correct according to the date the pass was booked. 

Expected:
* The date displayed on email confirmation should be the date that the pass was actually booked for. 

Issue:
* The email confirmation for the Garibaldi park, Cheakamus subarea shows a date which is one day ahead of the date the pass was actually booked for. 
https://github.com/user-attachments/assets/751c9164-a89b-4095-9e6b-8d76c80b2d9f
![Image](https://github.com/user-attachments/assets/2cf927f7-e0c2-4cbd-85e7-515b5e9770b2)
![Image](https://github.com/user-attachments/assets/391ff351-8cd8-45b9-ac71-e0c1805bf881)

**Comment by Christopher-walsh22** [comment]
@manuji @LindsayMacfarlane 

I have been digging into this issue and just wanted to highlight some of what is happening. I don't think this is something that we need to action, but might be good to explore during any reworks of how we want to manage passes in the future but in order to address this we would need to fundamentally change parts of the DUP.
 
This issue has been created by having the AM opening hour set after the PM pass start time. The opening hour can be set, but the PM passes start at 1pm. While testing ticket #424 I believe Manuji changed the AM opening hour to 5pm. This makes sense for testing purposes, but I cant see any reason why this would be mirrored in the PROD environment as it would go against the booking instructions written on the website, and also just create an oxymoron of what type of pass a user would require.  If we need to safeguard against an admin accidentally doing this we could set limitations on the admin side, but this has never been a problem before.
 
Please let me know how you want to proceed, I can either change the opening hour back to 7am so Manuji can complete her testing, or we can discuss a best path forward.
 
An additional note: The pass created in Manujis example was actually stored in the DB for the 30th, so the email was sending the correct date. It was the logic from the API which would not allow the AM pass to be created after the PM start time.

**Comment by LindsayMacfarlane** [comment]
Thank you @Christopher-walsh22 and @manuji - 

Based on your input above Chris, could we change the opening hour back to 7am for Manuji to complete her testing? 

I'd also like to hear how we should best track some of these issues as we start to scope bringing DUP into the new reservation system.

cc @Dianadec ^flag on the last sentence ;)

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* verified when the booking window start time set to 7am, the above issue cannot be recreated. 
* But I highly recommend adding a backlog item to address this behaviour as we have the option to change the booking openning time from the Admin panel as Chris mentioned in his previous comment. 
* Closing the ticket. 

FYI @LindsayMacfarlane
